### ISSUE TITLE
Timezone issues for PV1,2,3 entities calculated on the dongle

### ISSUE THREAD

**Issue by tomatensaus** [tomatensaus/DeyeSolarDesktop#24]
It would appear that entities calculated on the dongle does not follow the home assistant timezone

Entities affected:

```
sensor.deyeinvertermaster_summary_total_pv1
sensor.deyeinvertermaster_summary_total_pv2
```

Workaround:
Add the entities below in your config, use them in your dashboard, just add the _fix  postfix to the ones affected.

```
sensor:
  - platform: integration
    name: deyeinvertermaster_summary_total_pv1_fix
    source: sensor.deyeinvertermaster_pv1_power
    method: left
    unit_prefix: k

  - platform: integration
    name: deyeinvertermaster_summary_total_pv2_fix
    source: sensor.deyeinvertermaster_pv1_power
    method: left
    unit_prefix: k

utility_meter:
  master_pv1_fix:
    name: deyeinvertermaster_summary_day_pv1_fix
    source: sensor.deyeinvertermaster_summary_total_pv1_fix
    cycle: daily

  master_pv2_fix:
    name: deyeinvertermaster_summary_day_pv2_fix
    source: sensor.deyeinvertermaster_summary_total_pv2_fix
    cycle: daily
```
